# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 565de12b85074e710de67f9b014ce1de031cdc4f860bdc6b1a3a77ff13779158523617f4e0b4bd7085fad468f51665e11e7d23766646d655d42f02ba7b664aed

test:
  secret_key_base: 54ae95116a6865ea5d24b27e159f4a0f714f20bcbe987f14feae6ea3cdf9bf3f752d70226c842a3c8fbeebe24ee274b9839ae470addda69c028651b1c71ab3eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
